application: moishetest
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: chatactoe.py

inbound_services:
- channel_presence
