import path from 'path';
import fs from 'fs/promises';
import { ExtensionApiMap } from './types';

// Fetch the latest version of the chrome types from storage
export const fetchChromeTypes = async (): Promise<Record<string, any>> => {
  // Bucket used to store processed types data
  const storageBucket = process.env.STORAGE_BUCKET;

  if (!storageBucket) {
    throw new Error('The STORAGE_BUCKET environment variable must be set.');
  }

  console.log('Fetching chrome types...');

  const response = await fetch(
    `https://storage.googleapis.com/download/storage/v1/b/${storageBucket}/o/chrome-types.json?alt=media`
  );
  return (await response.json()) as Record<string, any>;
};

// Sort every property of every API into properties, methods, events or types
export const toExtensionApiMap = async (
  chromeTypes: Record<string, any>
): Promise<ExtensionApiMap> => {
  // typedoc 0.28+ ships as ESM only, so it cannot be require()d from this
  // CommonJS module; load it dynamically instead.
  const { ReflectionKind } = await import('typedoc');
  const result: ExtensionApiMap = {};

  for (const [chromeApiKey, chromeApiDetails] of Object.entries(chromeTypes)) {
    const apiDetails: ExtensionApiMap[string] = {
      properties: [],
      methods: [],
      types: [],
      events: []
    };

    for (let property of chromeApiDetails._type.properties) {
      const name = property.name as string;

      // check property type
      let propertyType = 'types';
      if (property.kind & ReflectionKind.VariableOrProperty) {
        propertyType = 'properties';
      }
      if (
        property.type?.type === 'reference' &&
        ['CustomChromeEvent', 'events.Event', 'Event'].includes(
          property.type.name
        )
      ) {
        propertyType = 'events';
      }
      if (property.signatures) {
        propertyType = 'methods';
      }

      apiDetails[propertyType].push(name);
    }

    result[chromeApiKey] = apiDetails;
  }

  return result;
};

const run = async () => {
  const chromeTypes = await fetchChromeTypes();
  const result = await toExtensionApiMap(chromeTypes);

  console.log('Writing to file...');
  await fs.writeFile(
    path.join(__dirname, '../extension-apis.json'),
    JSON.stringify(
      {
        _comment:
          'This file is autogenerated by running `npm run prepare-chrome-types`, do not edit.',
        ...result
      },
      null,
      2
    )
  );
  console.log('Done!');
};

// Only run when invoked as a script, so the exports above stay importable.
if (require.main === module) {
  run();
}
